print("hello world")
print("Hamayal")
print("Hamayal Tariq")
print("Hello, I am Hamayal Tariq.")
print ("25")
print (2*3)
print ("2+5+9")
print ("Hello,","I ","am","Hamayal.")
print ("Hamayal","is","20","years","old.")
